object F_tabelaPersonagens: TF_tabelaPersonagens
  Left = 0
  Top = 0
  Align = alClient
  BorderStyle = bsDialog
  Caption = 'PERSONAGENS'
  ClientHeight = 464
  ClientWidth = 754
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  PixelsPerInch = 96
  TextHeight = 13
end
